version: "3.9"  # optional since v1.27.0
services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Christmas2020"
      ACCEPT_EULA: "Y"
    volumes:
      - "planningPokerDB:/var/opt/mssql"
    expose:
      - "1433"
    ports:
      - "1433:1433"

volumes:
   "planningPokerDB":